apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dokumentinnhenting
  namespace: aap
  labels:
    team: aap
    sub: dokumentinnhenting
spec:
  image: {{image}}
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  ingresses:
    - "https://aap-dokumentinnhenting.intern.dev.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  kafka:
    pool: nav-dev
    streams: true
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: dokumentinnhenting
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  env:
    - name: BEHANDLINGSFLYT_BASE_URL
      value: http://behandlingsflyt
    - name: BEHANDLINGSFLYT_SCOPE
      value: api://dev-gcp.aap.behandlingsflyt/.default
    - name: INTEGRASJON_BEHANDLINGSFLYT_AZP
      value: dev-gcp:aap:behandlingsflyt
    - name: INTEGRASJON_SYFO_BASE_URL
      value: http://isdialogmelding.teamsykefravr
    - name: INTEGRASJON_SYFO_SCOPE
      value: api://dev-gcp.teamsykefravr.isdialogmelding/.default
    - name: INTEGRASJON_SAF_URL_GRAPHQL
      value: https://saf-q2.dev-fss-pub.nais.io/graphql
    - name: INTEGRASJON_SAF_URL_REST
      value: https://saf-q2.dev-fss-pub.nais.io/rest
    - name: INTEGRASJON_SAF_SCOPE
      value: api://dev-fss.teamdokumenthandtering.saf/.default
    - name: INTEGRASJON_DOKARKIV_URL
      value: https://dokarkiv-q2.dev-fss-pub.nais.io
    - name: INTEGRASJON_DOKARKIV_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv/.default
    - name: INTEGRASJON_BREV_BASE_URL
      value: http://brev
    - name: INTEGRASJON_BREV_SCOPE
      value: api://dev-gcp.aap.brev/.default
    - name: INTEGRASJON_BREV_AZP
      value: dev-gcp:aap:brev
    - name: INTEGRASJON_SAKSBEHANDLING_AZP
      value: dev-gcp:aap:saksbehandling
  accessPolicy:
    inbound:
      rules:
        - application: behandlingsflyt
          permissions:
            roles:
              - "syfo-api"
        - application: paw-patrol
        - application: saksbehandling
    outbound:
      rules:
        - application: behandlingsflyt
        - application: brev
        - application: isdialogmelding
          namespace: teamsykefravr
      external:
        - host: saf.dev-fss-pub.nais.io
        - host: dokarkiv-q2.dev-fss-pub.nais.io
